FROM ubuntu:20.04
WORKDIR /~
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y openjdk-8-jdk-headless 
RUN apt-get install -y mysql-server 
RUN cd ~ 
RUN apt-get install -y wget
RUN wget https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.86/bin/apache-tomcat-8.5.86.tar.gz 
RUN tar -xvzf apache-tomcat-8.5.86.tar.gz 
WORKDIR /apache-tomcat-8.5.86/bin
CMD ["./startup.sh"]



EXPOSE 8888